# from http://jekyllrb.com/docs/continuous-integration/
language: ruby
rvm:
- 2.1
- 2.2
# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
install: gem install jekyll rdiscount pygments.rb #html-proofer
script: jekyll build #&& htmlproof ./_site --disable-external --only-4xx --check-html --check-favicon
# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

